[[ Bug 22946 ]] Update the engine to compile with Xcode 12
Changes:

1. Remove unused deprecated Framework that caused compile error on iOS 14  …
Fixes compile error:
- error: expected '('
MP_DEPRECATED_BEGIN("Use AVPlayerViewController in AVKit.", ios(3.2, 9.0))
^- error: expected 'push' or 'pop' after '#pragma clang attribute'

2. Fix error "implicit declaration of function X' is invalid in C99" by adding a proper flag in ios.gypi

3. Removed notifications code for iOS < 8, since the oldest iOS version we support is 8.0.
Fixes error:
error: no matching function for call to 'objc_msgSend'
objc_msgSend([UIApplication sharedApplication], sel_getUid("registerForRemoteNotificationTypes:"), t_allowed_notifications);

4. Added inclusion of missing header.
Fixes error:
/Users/administrator/Vulcan/slaves/build-mac-4-1/slave/try-community-universal-ios-iphoneos14_0/checkout/toolchain/lc-compile-ffi-java/src/main.c:73:17: error: implicit declaration of function 'SetOutputFile' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                SetOutputFile(argv[++argi]);
                ^
/Users/administrator/Vulcan/slaves/build-mac-4-1/slave/try-community-universal-ios-iphoneos14_0/checkout/toolchain/lc-compile-ffi-java/src/main.c:78:17: error: implicit declaration of function 'SetOutputLCBFile' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                SetOutputLCBFile(argv[++argi]);
                ^
/Users/administrator/Vulcan/slaves/build-mac-4-1/slave/try-community-universal-ios-iphoneos14_0/checkout/toolchain/lc-compile-ffi-java/src/main.c:83:17: error: implicit declaration of function 'SetOutputLCBModuleName' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                SetOutputLCBModuleName(argv[++argi]);